# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-12-05 10:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Brand')),
            ],
            options={
                'db_table': 'brand',
                'verbose_name': 'Brand',
                'verbose_name_plural': 'Brands',
            },
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(verbose_name='Graduation year')),
                ('price', models.IntegerField(verbose_name='Car price')),
                ('owner', models.CharField(max_length=50, verbose_name='Owner car')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='brand', related_query_name='brand', to='car.Brand', verbose_name='Car brand')),
            ],
            options={
                'ordering': ['-brand', 'pattern', '-year', '-price'],
                'db_table': 'customer',
                'verbose_name': 'Customers',
                'verbose_name_plural': 'Customer',
            },
        ),
        migrations.CreateModel(
            name='Pattern',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Pattern')),
            ],
            options={
                'db_table': 'pattern',
                'verbose_name': 'Pattern',
                'verbose_name_plural': 'Patterns',
            },
        ),
        migrations.AddField(
            model_name='car',
            name='pattern',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pattern', related_query_name='pattern', to='car.Pattern', verbose_name='Cur model'),
        ),
    ]
